// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.0
// 	protoc        v3.14.0
// source: checkYoutube.proto

package api

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CheckRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Key    string `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	IdPlay string `protobuf:"bytes,2,opt,name=idPlay,proto3" json:"idPlay,omitempty"`
}

func (x *CheckRequest) Reset() {
	*x = CheckRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_checkYoutube_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CheckRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckRequest) ProtoMessage() {}

func (x *CheckRequest) ProtoReflect() protoreflect.Message {
	mi := &file_checkYoutube_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckRequest.ProtoReflect.Descriptor instead.
func (*CheckRequest) Descriptor() ([]byte, []int) {
	return file_checkYoutube_proto_rawDescGZIP(), []int{0}
}

func (x *CheckRequest) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *CheckRequest) GetIdPlay() string {
	if x != nil {
		return x.IdPlay
	}
	return ""
}

type CheckResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	List string `protobuf:"bytes,1,opt,name=list,proto3" json:"list,omitempty"`
}

func (x *CheckResponse) Reset() {
	*x = CheckResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_checkYoutube_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CheckResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckResponse) ProtoMessage() {}

func (x *CheckResponse) ProtoReflect() protoreflect.Message {
	mi := &file_checkYoutube_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckResponse.ProtoReflect.Descriptor instead.
func (*CheckResponse) Descriptor() ([]byte, []int) {
	return file_checkYoutube_proto_rawDescGZIP(), []int{1}
}

func (x *CheckResponse) GetList() string {
	if x != nil {
		return x.List
	}
	return ""
}

var File_checkYoutube_proto protoreflect.FileDescriptor

var file_checkYoutube_proto_rawDesc = []byte{
	0x0a, 0x12, 0x63, 0x68, 0x65, 0x63, 0x6b, 0x59, 0x6f, 0x75, 0x74, 0x75, 0x62, 0x65, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x12, 0x07, 0x77, 0x65, 0x62, 0x50, 0x61, 0x67, 0x65, 0x22, 0x38, 0x0a,
	0x0c, 0x43, 0x68, 0x65, 0x63, 0x6b, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x10, 0x0a,
	0x03, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x12,
	0x16, 0x0a, 0x06, 0x69, 0x64, 0x50, 0x6c, 0x61, 0x79, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x06, 0x69, 0x64, 0x50, 0x6c, 0x61, 0x79, 0x22, 0x23, 0x0a, 0x0d, 0x43, 0x68, 0x65, 0x63, 0x6b,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x6c, 0x69, 0x73, 0x74,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6c, 0x69, 0x73, 0x74, 0x32, 0x48, 0x0a, 0x0c,
	0x63, 0x68, 0x65, 0x63, 0x6b, 0x59, 0x6f, 0x75, 0x74, 0x75, 0x62, 0x65, 0x12, 0x38, 0x0a, 0x05,
	0x43, 0x68, 0x65, 0x63, 0x6b, 0x12, 0x15, 0x2e, 0x77, 0x65, 0x62, 0x50, 0x61, 0x67, 0x65, 0x2e,
	0x43, 0x68, 0x65, 0x63, 0x6b, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x16, 0x2e, 0x77,
	0x65, 0x62, 0x50, 0x61, 0x67, 0x65, 0x2e, 0x43, 0x68, 0x65, 0x63, 0x6b, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x42, 0x0c, 0x5a, 0x0a, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x2f, 0x61, 0x70, 0x69, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_checkYoutube_proto_rawDescOnce sync.Once
	file_checkYoutube_proto_rawDescData = file_checkYoutube_proto_rawDesc
)

func file_checkYoutube_proto_rawDescGZIP() []byte {
	file_checkYoutube_proto_rawDescOnce.Do(func() {
		file_checkYoutube_proto_rawDescData = protoimpl.X.CompressGZIP(file_checkYoutube_proto_rawDescData)
	})
	return file_checkYoutube_proto_rawDescData
}

var file_checkYoutube_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_checkYoutube_proto_goTypes = []interface{}{
	(*CheckRequest)(nil),  // 0: webPage.CheckRequest
	(*CheckResponse)(nil), // 1: webPage.CheckResponse
}
var file_checkYoutube_proto_depIdxs = []int32{
	0, // 0: webPage.checkYoutube.Check:input_type -> webPage.CheckRequest
	1, // 1: webPage.checkYoutube.Check:output_type -> webPage.CheckResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_checkYoutube_proto_init() }
func file_checkYoutube_proto_init() {
	if File_checkYoutube_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_checkYoutube_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CheckRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_checkYoutube_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CheckResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_checkYoutube_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_checkYoutube_proto_goTypes,
		DependencyIndexes: file_checkYoutube_proto_depIdxs,
		MessageInfos:      file_checkYoutube_proto_msgTypes,
	}.Build()
	File_checkYoutube_proto = out.File
	file_checkYoutube_proto_rawDesc = nil
	file_checkYoutube_proto_goTypes = nil
	file_checkYoutube_proto_depIdxs = nil
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// CheckYoutubeClient is the client API for CheckYoutube service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type CheckYoutubeClient interface {
	Check(ctx context.Context, in *CheckRequest, opts ...grpc.CallOption) (*CheckResponse, error)
}

type checkYoutubeClient struct {
	cc grpc.ClientConnInterface
}

func NewCheckYoutubeClient(cc grpc.ClientConnInterface) CheckYoutubeClient {
	return &checkYoutubeClient{cc}
}

func (c *checkYoutubeClient) Check(ctx context.Context, in *CheckRequest, opts ...grpc.CallOption) (*CheckResponse, error) {
	out := new(CheckResponse)
	err := c.cc.Invoke(ctx, "/webPage.checkYoutube/Check", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CheckYoutubeServer is the server API for CheckYoutube service.
type CheckYoutubeServer interface {
	Check(context.Context, *CheckRequest) (*CheckResponse, error)
}

// UnimplementedCheckYoutubeServer can be embedded to have forward compatible implementations.
type UnimplementedCheckYoutubeServer struct {
}

func (*UnimplementedCheckYoutubeServer) Check(context.Context, *CheckRequest) (*CheckResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Check not implemented")
}

func RegisterCheckYoutubeServer(s *grpc.Server, srv CheckYoutubeServer) {
	s.RegisterService(&_CheckYoutube_serviceDesc, srv)
}

func _CheckYoutube_Check_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CheckRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CheckYoutubeServer).Check(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/webPage.checkYoutube/Check",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CheckYoutubeServer).Check(ctx, req.(*CheckRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _CheckYoutube_serviceDesc = grpc.ServiceDesc{
	ServiceName: "webPage.checkYoutube",
	HandlerType: (*CheckYoutubeServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Check",
			Handler:    _CheckYoutube_Check_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "checkYoutube.proto",
}
